export type CatalogOrigin = "UK" | "USA" | "China" | "Zimbabwe"

export type CatalogProduct = {
  title: string
  handle: string
  sku: string
  manufacturer: string
  supplier_origin: CatalogOrigin
  description: string
  categories: string[]
  usd: number
  stock: number
  delivery_window_days: number
  sourcing_type: "in_stock" | "pre_order" | "quote_only"
  specs: Record<string, string>
}

const para = (...parts: string[]) => parts.join("\n\n")

export const KONDUIT_CATALOG: CatalogProduct[] = [
  {
    title: "ThinkPad T14 Gen 5",
    handle: "lenovo-thinkpad-t14-gen-5",
    sku: "21ML000EUK",
    manufacturer: "Lenovo",
    supplier_origin: "UK",
    description: para(
      "A 14-inch business laptop for finance, operations and field managers who need a machine that survives daily travel and a full workday unplugged.",
      "It suits teams standardising on Intel Core Ultra with 32 GB of memory and a 1 TB NVMe drive. We quote the UK channel configuration unless you specify otherwise.",
      "The unit ships with a 65 W charger, a standard international keyboard layout and the manufacturer's documentation pack.",
      "Lenovo Premier Support warranty is three years on parts and labour, stated again on the written quote."
    ),
    categories: ["Infrastructure"],
    usd: 1899,
    stock: 12,
    delivery_window_days: 7,
    sourcing_type: "in_stock",
    specs: {
      processor: "Intel Core Ultra 7",
      memory: "32 GB DDR5",
      storage: "1 TB NVMe SSD",
      networking: "Wi-Fi 6E, Bluetooth, optional LTE",
      display: "14-inch WUXGA",
      power: "65 W USB-C charger",
      warranty: "3-year Lenovo Premier Support",
      compliance: "Energy Star, EPEAT Gold",
    },
  },
  {
    title: "OptiPlex 7020 Tower",
    handle: "dell-optiplex-7020-tower",
    sku: "7020-TWR-I7",
    manufacturer: "Dell",
    supplier_origin: "USA",
    description: para(
      "A compact tower desktop for accounts, reception and branch offices that need more expandability than a laptop.",
      "It suits SMEs replacing ageing OptiPlex floors with Intel Core i7, 16 GB of memory and a 512 GB SSD. Extra drive bays are available on the quote if you keep local file shares.",
      "Included: tower chassis, standard keyboard and mouse, and Dell's setup documentation. Displays are quoted separately.",
      "Dell ProSupport warranty is three years. On-site options for Harare can be added to the quote."
    ),
    categories: ["Infrastructure"],
    usd: 1299,
    stock: 0,
    delivery_window_days: 12,
    sourcing_type: "pre_order",
    specs: {
      processor: "Intel Core i7",
      memory: "16 GB DDR5",
      storage: "512 GB SSD",
      networking: "Gigabit Ethernet, Wi-Fi optional",
      form_factor: "Tower",
      power: "300 W PSU",
      warranty: "3-year Dell ProSupport",
      compliance: "Energy Star",
    },
  },
  {
    title: "Catalyst 9200L 24-port Switch",
    handle: "cisco-catalyst-9200l-24p",
    sku: "C9200L-24P-4G-E",
    manufacturer: "Cisco",
    supplier_origin: "USA",
    description: para(
      "A 24-port PoE+ access switch for office floors, clinics and campus wiring closets that need Cisco's Catalyst feature set without a full 9300 chassis.",
      "It suits network refreshes that already run Cisco DNA or need StackWise-160. Four 1G SFP uplinks are included. Optics are quoted as a line item.",
      "The shipment includes the switch, rack ears and the power cable specified on the quote. Smart licences are confirmed before we place the PO.",
      "Cisco limited lifetime hardware warranty applies, with the service SKU written on the quote."
    ),
    categories: ["Infrastructure"],
    usd: 2499,
    stock: 0,
    delivery_window_days: 14,
    sourcing_type: "pre_order",
    specs: {
      ports: "24 x 1GbE PoE+",
      uplinks: "4 x 1G SFP",
      stacking: "StackWise-160",
      switching_capacity: "56 Gbps",
      power: "PoE budget per Cisco 9200L data sheet",
      warranty: "Cisco limited lifetime hardware",
      compliance: "Safety and EMC as shipped by Cisco",
    },
  },
  {
    title: "PowerEdge R740 Rack Server",
    handle: "dell-poweredge-r740",
    sku: "R740-BASE",
    manufacturer: "Dell",
    supplier_origin: "USA",
    description: para(
      "A 2U dual-socket rack server for virtualisation, line-of-business applications and departmental databases in a Harare or regional data hall.",
      "It suits buyers who need Xeon Scalable processors, dense 2.5-inch drive capacity and iDRAC remote management. We spec CPU, memory and storage against your workload on the quote.",
      "A typical quote includes rails, a bezel, dual hot-swap power supplies and the iDRAC licence tier you choose. Operating system media is optional.",
      "Dell ProSupport or ProSupport Plus is stated on the quote. Standard cover is three years, next-business-day parts where Dell offers it in the region."
    ),
    categories: ["Infrastructure"],
    usd: 4899,
    stock: 0,
    delivery_window_days: 21,
    sourcing_type: "pre_order",
    specs: {
      processor: "Dual Intel Xeon Scalable (quoted configuration)",
      memory: "Up to 3 TB DDR4 (quoted DIMM count)",
      storage: "Up to 24 x 2.5-inch drives",
      networking: "rNDC plus optional PCIe NICs",
      form_factor: "2U rack",
      power: "Dual hot-swap PSUs",
      warranty: "3-year Dell ProSupport, stated on quote",
      compliance: "Dell EMC regulatory pack",
    },
  },
  {
    title: "HPE MSA 2060 Storage",
    handle: "hpe-msa-2060",
    sku: "R0Q85A",
    manufacturer: "HPE",
    supplier_origin: "USA",
    description: para(
      "A dual-controller hybrid storage array for branches that have outgrown direct-attached disks and need shared block storage.",
      "It suits VMware and Hyper-V hosts that want iSCSI, Fibre Channel or SAS connectivity and room to grow toward 336 TB.",
      "Controllers ship in a pair. Disk packs, SFPs and host bus adapters are quoted as separate lines so you only pay for the protocol you run.",
      "HPE Foundation Care or Pointnext cover is written on the quote. Standard hardware warranty follows the MSA 2060 terms."
    ),
    categories: ["Infrastructure"],
    usd: 6599,
    stock: 0,
    delivery_window_days: 21,
    sourcing_type: "pre_order",
    specs: {
      controllers: "Dual active controllers",
      capacity: "Up to 336 TB raw",
      protocols: "iSCSI, Fibre Channel or SAS",
      form_factor: "2U",
      power: "Redundant PSUs",
      warranty: "HPE Foundation Care, stated on quote",
      compliance: "HPE regulatory documentation",
    },
  },
  {
    title: "PowerEdge T350 Tower Server",
    handle: "dell-poweredge-t350",
    sku: "T350-BASE",
    manufacturer: "Dell",
    supplier_origin: "USA",
    description: para(
      "An entry-level tower server for offices that need a first on-premises host without a full rack room.",
      "It suits file, print, domain and light virtualisation workloads on a single Xeon E-2300 series processor.",
      "The quote includes the tower chassis, a cabled or hot-swap drive bay option, and iDRAC Basic or Express. A rack conversion kit can be added.",
      "Dell ProSupport is three years unless you ask for a longer term on the quote."
    ),
    categories: ["Infrastructure"],
    usd: 2199,
    stock: 0,
    delivery_window_days: 16,
    sourcing_type: "pre_order",
    specs: {
      processor: "Intel Xeon E-2300 series (quoted SKU)",
      memory: "Up to 128 GB DDR4",
      storage: "Up to 8 x 3.5-inch drives",
      networking: "Dual 1GbE LOM",
      form_factor: "Tower, rack-convertible",
      power: "Single or redundant PSU",
      warranty: "3-year Dell ProSupport",
      compliance: "Dell regulatory pack",
    },
  },
  {
    title: "FortiGate 60F Firewall",
    handle: "fortinet-fortigate-60f",
    sku: "FG-60F",
    manufacturer: "Fortinet",
    supplier_origin: "UK",
    description: para(
      "A desktop firewall appliance for SME internet edges, VPN hubs and branch offices that need FortiOS inspection without a 1U chassis.",
      "It suits sites with a handful of WAN links and a need for SSL VPN or IPsec back to Harare.",
      "Hardware ships with the default power brick. FortiCare and FortiGuard bundles are quoted as a separate annual line.",
      "Fortinet hardware warranty follows the FortiCare SKU on the quote."
    ),
    categories: ["Infrastructure"],
    usd: 895,
    stock: 4,
    delivery_window_days: 10,
    sourcing_type: "in_stock",
    specs: {
      firewall_throughput: "10 Gbps",
      vpn_throughput: "6.5 Gbps IPsec",
      ports: "7 x GE RJ45, 2 x GE WAN",
      form_factor: "Desktop",
      power: "External PSU",
      warranty: "FortiCare, stated on quote",
      compliance: "Fortinet regulatory documentation",
    },
  },
  {
    title: "Cat6 UTP cable, per metre",
    handle: "structured-cabling-cat6-per-metre",
    sku: "CAB-CAT6-M",
    manufacturer: "Curated",
    supplier_origin: "China",
    description: para(
      "A per-metre Cat6 UTP line for new floors, camera runs and patch-field expansions when you already have a bill of quantities.",
      "It suits contractors and facilities teams who want landed copper quoted with the same customs desk as the active equipment.",
      "We quote jacket colour, box or reel length, and any LSZH requirement on the written quote. Termination and testing are a separate labour line.",
      "Cable carries the manufacturer's channel warranty when installed to their specification. We state that on the quote."
    ),
    categories: ["Infrastructure"],
    usd: 2.4,
    stock: 500,
    delivery_window_days: 18,
    sourcing_type: "in_stock",
    specs: {
      category: "Cat6 UTP",
      unit: "Per metre",
      conductor: "23 AWG copper",
      jacket: "PVC or LSZH, stated on quote",
      warranty: "Manufacturer channel warranty when certified",
      compliance: "ISO/IEC 11801 Class E",
    },
  },
  {
    title: "APC NetShelter 42U rack accessories kit",
    handle: "apc-netshelter-42u-accessories",
    sku: "AR8136BLK-KIT",
    manufacturer: "APC",
    supplier_origin: "UK",
    description: para(
      "A kit of blanking panels, cable managers and shelf hardware for a 42U NetShelter or equivalent EIA rack.",
      "It suits data-hall tidy-ups and new racks that arrived without airflow or cable management.",
      "Contents are listed on the quote: typically 1U blanks, vertical managers and a fixed shelf. Colour is black unless you specify otherwise.",
      "APC hardware warranty applies to branded parts in the kit."
    ),
    categories: ["Infrastructure"],
    usd: 429,
    stock: 6,
    delivery_window_days: 14,
    sourcing_type: "in_stock",
    specs: {
      rack_standard: "19-inch EIA, 42U",
      contents: "Blanks, managers and shelf, stated on quote",
      colour: "Black",
      warranty: "APC hardware warranty",
      compliance: "RoHS",
    },
  },
  {
    title: "HPE ProLiant DL360 Gen10 Plus",
    handle: "hpe-proliant-dl360-gen10-plus",
    sku: "P38995-B21",
    manufacturer: "HPE",
    supplier_origin: "USA",
    description: para(
      "A 1U dual-socket server for dense compute in a rack that cannot spare a second U.",
      "It suits virtualisation clusters and application hosts that want Xeon Scalable performance with iLO remote management.",
      "Rails, iLO licence and power supply redundancy are confirmed on the quote before we place the order.",
      "HPE Pointnext support duration is written on the quote. Three years is the usual starting point."
    ),
    categories: ["Infrastructure"],
    usd: 4299,
    stock: 0,
    delivery_window_days: 21,
    sourcing_type: "pre_order",
    specs: {
      processor: "Dual Intel Xeon Scalable (quoted SKU)",
      memory: "Up to 4 TB DDR4",
      storage: "8 or 10 SFF bays, quoted",
      form_factor: "1U rack",
      power: "Flexible Slot redundant PSUs",
      warranty: "HPE Pointnext, stated on quote",
      compliance: "HPE regulatory pack",
    },
  },
  {
    title: "Cisco ISR 4331 Router",
    handle: "cisco-isr-4331",
    sku: "ISR4331-K9",
    manufacturer: "Cisco",
    supplier_origin: "USA",
    description: para(
      "A modular branch router for WAN aggregation, voice gateways and sites that still need IOS XE services on the edge.",
      "It suits replacements of older ISR G2 boxes and new branches that need NIM slots for serial, voice or extra Ethernet.",
      "The base chassis is quoted with the IOS feature set you name. NIM modules and licences are separate lines.",
      "Cisco hardware warranty and Smart Net options are stated on the quote."
    ),
    categories: ["Infrastructure"],
    usd: 3199,
    stock: 0,
    delivery_window_days: 18,
    sourcing_type: "pre_order",
    specs: {
      throughput: "Up to 100 Mbps, performance licence up to 300 Mbps",
      slots: "2 NIM, 1 SM-X, 1 ISC",
      form_factor: "1U",
      power: "Internal AC",
      warranty: "Cisco limited warranty plus Smart Net on quote",
      compliance: "Cisco regulatory documentation",
    },
  },
  {
    title: "Dell PowerSwitch N3248P-ON",
    handle: "dell-powerswitch-n3248p-on",
    sku: "N3248P-ON",
    manufacturer: "Dell",
    supplier_origin: "USA",
    description: para(
      "A 48-port PoE+ access switch for floors that prefer Dell OS10 or need a non-Cisco alternative in the same rack.",
      "It suits camera-heavy and Wi-Fi-heavy closets that need more than 24 PoE ports.",
      "Optics, stacking cables and a spare PSU are quoted if you ask for them.",
      "Dell ProSupport for networking is written on the quote."
    ),
    categories: ["Infrastructure"],
    usd: 2799,
    stock: 0,
    delivery_window_days: 16,
    sourcing_type: "pre_order",
    specs: {
      ports: "48 x 1GbE PoE+",
      uplinks: "4 x 10G SFP+",
      operating_system: "Dell OS10",
      form_factor: "1U",
      warranty: "Dell ProSupport for networking",
      compliance: "Dell regulatory pack",
    },
  },
  {
    title: "APC Rack PDU, metered, 16 A",
    handle: "apc-rack-pdu-metered-16a",
    sku: "AP8858",
    manufacturer: "APC",
    supplier_origin: "UK",
    description: para(
      "A metered vertical PDU for racks that need current visibility before the next server lands.",
      "It suits data halls that already standardised on APC and want C13 outlets on a 16 A feed.",
      "Plug type and voltage are confirmed against your site before we order. A mismatched inlet is expensive to fix later.",
      "APC warranty follows the PDU series data sheet and is restated on the quote."
    ),
    categories: ["Infrastructure"],
    usd: 649,
    stock: 3,
    delivery_window_days: 14,
    sourcing_type: "in_stock",
    specs: {
      inlet: "16 A, type confirmed on quote",
      outlets: "C13, count per SKU",
      metering: "Current metering",
      form_factor: "Vertical 0U",
      warranty: "APC hardware warranty",
      compliance: "CE, RoHS",
    },
  },
  {
    title: "UniFi U6 Pro Access Point",
    handle: "ubiquiti-unifi-u6-pro",
    sku: "U6-Pro",
    manufacturer: "Ubiquiti",
    supplier_origin: "UK",
    description: para(
      "A Wi-Fi 6 ceiling access point for offices, clinics and warehouses that already run UniFi Network.",
      "It suits indoor coverage where 5.3 Gbps aggregate and 2.5 GbE uplink are enough. Outdoor and high-density halls should use a different SKU.",
      "The carton includes the AP, a ceiling mount and the usual UniFi documentation. A PoE injector is optional if your switch is not PoE.",
      "Ubiquiti limited hardware warranty is two years unless the quote states a different channel term."
    ),
    categories: ["Telecoms", "Telecoms Devices"],
    usd: 179,
    stock: 25,
    delivery_window_days: 5,
    sourcing_type: "in_stock",
    specs: {
      wifi: "Wi-Fi 6, 5.3 Gbps aggregate",
      uplink: "2.5 GbE",
      power: "PoE, 802.3at",
      mount: "Ceiling or wall",
      warranty: "2-year Ubiquiti limited hardware",
      compliance: "Ubiquiti regulatory documentation",
    },
  },
  {
    title: "Site Survey & Network Design",
    handle: "telecoms-site-survey",
    sku: "TEL-SURVEY-001",
    manufacturer: "Konduit",
    supplier_origin: "Zimbabwe",
    description: para(
      "An on-site survey and design engagement for campus, multi-site or greenfield networks in Zimbabwe and neighbouring markets.",
      "It suits operators and enterprises that need a bill of materials, heat maps or a migration plan before they buy hardware.",
      "The quote states the sites, nights on the ground and whether we include a written design pack. Hardware is a separate order.",
      "Workmanship on the design pack is covered by the service quote, not a manufacturer warranty."
    ),
    categories: ["Telecoms", "Telecoms Infrastructure Services"],
    usd: 0,
    stock: 0,
    delivery_window_days: 14,
    sourcing_type: "quote_only",
    specs: {
      engagement: "On-site survey and design",
      deliverable: "Written design pack, stated on quote",
      coverage: "Zimbabwe and neighbouring markets",
      warranty: "Service terms on the specific quote",
    },
  },
  {
    title: "UniFi U6 Enterprise Access Point",
    handle: "ubiquiti-unifi-u6-enterprise",
    sku: "U6-Enterprise",
    manufacturer: "Ubiquiti",
    supplier_origin: "UK",
    description: para(
      "A higher-density Wi-Fi 6E access point for boardrooms, lecture rooms and busy open-plan floors.",
      "It suits sites that already standardised on UniFi and need the 6 GHz radio as well as 5 GHz.",
      "Mounting hardware is in the box. A 2.5 GbE PoE++ switch port is required for full performance.",
      "Ubiquiti limited hardware warranty is two years."
    ),
    categories: ["Telecoms", "Telecoms Devices"],
    usd: 279,
    stock: 10,
    delivery_window_days: 7,
    sourcing_type: "in_stock",
    specs: {
      wifi: "Wi-Fi 6E",
      uplink: "2.5 GbE",
      power: "PoE++, 802.3bt",
      warranty: "2-year Ubiquiti limited hardware",
      compliance: "Ubiquiti regulatory documentation",
    },
  },
  {
    title: "UniFi Dream Machine Pro",
    handle: "ubiquiti-unifi-dream-machine-pro",
    sku: "UDM-Pro",
    manufacturer: "Ubiquiti",
    supplier_origin: "UK",
    description: para(
      "A 1U UniFi gateway and controller for sites that want routing, security and NVR in one appliance.",
      "It suits head offices and small campuses that do not want a separate Cloud Key and security gateway.",
      "HDD for Protect is optional and quoted if you want onboard recording.",
      "Ubiquiti limited hardware warranty is two years."
    ),
    categories: ["Telecoms", "Telecoms Devices"],
    usd: 399,
    stock: 6,
    delivery_window_days: 7,
    sourcing_type: "in_stock",
    specs: {
      form_factor: "1U rack",
      wan: "10G SFP+ and 2.5 GbE",
      lan: "8 x 1GbE",
      storage: "Optional 3.5-inch HDD bay",
      warranty: "2-year Ubiquiti limited hardware",
      compliance: "Ubiquiti regulatory documentation",
    },
  },
  {
    title: "MikroTik hAP ax3",
    handle: "mikrotik-hap-ax3",
    sku: "C53UiG+5HPaxD2HPaxD",
    manufacturer: "MikroTik",
    supplier_origin: "UK",
    description: para(
      "A Wi-Fi 6 desktop router for small offices and pop-up sites that want RouterOS without a rack.",
      "It suits IT teams who already operate MikroTik and need a spare or a branch kit they can clone from a backup.",
      "The carton includes the router and power supply. Outdoor antennas are not included.",
      "MikroTik standard hardware warranty applies, restated on the quote."
    ),
    categories: ["Telecoms", "Telecoms Devices"],
    usd: 129,
    stock: 18,
    delivery_window_days: 6,
    sourcing_type: "in_stock",
    specs: {
      wifi: "Wi-Fi 6 dual band",
      ports: "5 x 1GbE, 1 x 2.5GbE",
      os: "RouterOS",
      power: "24 V DC or PoE in",
      warranty: "MikroTik standard hardware",
      compliance: "CE",
    },
  },
  {
    title: "MikroTik CCR2004-1G-12S+2XS",
    handle: "mikrotik-ccr2004-12s",
    sku: "CCR2004-1G-12S+2XS",
    manufacturer: "MikroTik",
    supplier_origin: "UK",
    description: para(
      "A 1U Cloud Core Router for ISP edges, campus cores and sites that terminate many SFP+ links.",
      "It suits teams that want RouterOS throughput without a Cisco or Juniper licence model.",
      "SFP+ optics are quoted separately. Dual redundant power is on the SKU.",
      "MikroTik hardware warranty is stated on the quote."
    ),
    categories: ["Telecoms", "Telecoms Devices"],
    usd: 695,
    stock: 2,
    delivery_window_days: 10,
    sourcing_type: "pre_order",
    specs: {
      ports: "12 x SFP+, 2 x 25G SFP28, 1 x 1GbE",
      form_factor: "1U",
      os: "RouterOS",
      power: "Dual redundant PSUs",
      warranty: "MikroTik hardware warranty",
      compliance: "CE",
    },
  },
  {
    title: "Ubiquiti airFiber 60 LR",
    handle: "ubiquiti-airfiber-60-lr",
    sku: "AF60-LR",
    manufacturer: "Ubiquiti",
    supplier_origin: "USA",
    description: para(
      "A 60 GHz point-to-point radio for building-to-building links where fibre is slow or expensive to pull.",
      "It suits campuses and industrial parks with clear line of sight. Weather and distance are confirmed on the survey or quote.",
      "A pair is required for a link. Mounts and alignment tools are listed on the quote.",
      "Ubiquiti limited hardware warranty is one year on airFiber unless the channel states otherwise."
    ),
    categories: ["Telecoms", "Telecoms Devices"],
    usd: 429,
    stock: 0,
    delivery_window_days: 14,
    sourcing_type: "pre_order",
    specs: {
      band: "60 GHz",
      use: "Point-to-point",
      range: "Stated on quote after path check",
      power: "Passive PoE",
      warranty: "Ubiquiti airFiber limited hardware",
      compliance: "Ubiquiti regulatory documentation",
    },
  },
  {
    title: "Ubiquiti NanoStation 5AC",
    handle: "ubiquiti-nanostation-5ac",
    sku: "NS-5AC",
    manufacturer: "Ubiquiti",
    supplier_origin: "UK",
    description: para(
      "A 5 GHz CPE radio for last-mile and short point-to-point hops on airMAX.",
      "It suits WISPs and estates that already use NanoStation and need more subscriber units.",
      "Each quote line is a single radio. A link needs two. PoE injectors can be added.",
      "Ubiquiti limited hardware warranty applies."
    ),
    categories: ["Telecoms", "Telecoms Devices"],
    usd: 119,
    stock: 14,
    delivery_window_days: 8,
    sourcing_type: "in_stock",
    specs: {
      band: "5 GHz airMAX ac",
      gain: "16 dBi",
      power: "24 V passive PoE",
      warranty: "Ubiquiti limited hardware",
      compliance: "Ubiquiti regulatory documentation",
    },
  },
  {
    title: "Starlink Business kit",
    handle: "starlink-business-kit",
    sku: "STL-BIZ-KIT",
    manufacturer: "Starlink",
    supplier_origin: "USA",
    description: para(
      "A Starlink Business hardware kit for sites that need a backup or primary path where terrestrial last-mile is unreliable.",
      "It suits mines, farms and disaster-recovery rooms. Service subscription is not included and must be held by the customer in a supported country.",
      "The quote covers the dish, router and stand as supplied in the Business kit. Customs treatment is confirmed before we order.",
      "Hardware warranty is Starlink's, stated on the quote. Airtime is never sold as Konduit warranty."
    ),
    categories: ["Telecoms", "Telecoms Devices"],
    usd: 2500,
    stock: 0,
    delivery_window_days: 28,
    sourcing_type: "pre_order",
    specs: {
      service: "Customer-held Starlink Business subscription",
      contents: "Dish, router and stand as supplied",
      power: "As per Starlink Business kit",
      warranty: "Starlink hardware warranty on quote",
      compliance: "Import permits confirmed per shipment",
    },
  },
  {
    title: "Cisco IP Phone 8841",
    handle: "cisco-ip-phone-8841",
    sku: "CP-8841-K9",
    manufacturer: "Cisco",
    supplier_origin: "USA",
    description: para(
      "A colour IP handset for offices that run Cisco UCM or a compatible SIP platform.",
      "It suits reception and manager desks that need a wired PoE phone rather than a soft client.",
      "Power is PoE. A power brick is optional. Firmware compatibility is checked against your call control on the quote.",
      "Cisco limited hardware warranty applies."
    ),
    categories: ["Telecoms", "Telecoms Devices"],
    usd: 249,
    stock: 8,
    delivery_window_days: 12,
    sourcing_type: "in_stock",
    specs: {
      display: "5-inch colour",
      lines: "5",
      power: "PoE 802.3af",
      warranty: "Cisco limited hardware",
      compliance: "Cisco regulatory documentation",
    },
  },
  {
    title: "UniFi Switch Lite 8 PoE",
    handle: "ubiquiti-unifi-switch-lite-8-poe",
    sku: "USW-Lite-8-PoE",
    manufacturer: "Ubiquiti",
    supplier_origin: "UK",
    description: para(
      "An eight-port UniFi PoE switch for small closets, till points and camera cupboards.",
      "It suits sites that already use UniFi Network and need a compact fanless switch.",
      "The external power supply is included. It is not a rack unit.",
      "Ubiquiti limited hardware warranty is one year on this series unless the quote says otherwise."
    ),
    categories: ["Telecoms", "Telecoms Devices"],
    usd: 109,
    stock: 20,
    delivery_window_days: 5,
    sourcing_type: "in_stock",
    specs: {
      ports: "8 x GbE, 4 PoE",
      poe_budget: "52 W",
      form_factor: "Desktop",
      warranty: "Ubiquiti limited hardware",
      compliance: "Ubiquiti regulatory documentation",
    },
  },
  {
    title: "MikroTik Audience",
    handle: "mikrotik-audience",
    sku: "RBD25G-5HPacQD2HPnD",
    manufacturer: "MikroTik",
    supplier_origin: "UK",
    description: para(
      "A tri-band mesh access point for homes converted to offices and small floors that want RouterOS mesh.",
      "It suits sites that already operate MikroTik and do not want a UniFi controller.",
      "The unit is powered by the included PSU or PoE. Additional Audience nodes are quoted per unit.",
      "MikroTik hardware warranty applies."
    ),
    categories: ["Telecoms", "Telecoms Devices"],
    usd: 169,
    stock: 7,
    delivery_window_days: 8,
    sourcing_type: "in_stock",
    specs: {
      wifi: "Tri-band, including 4x4 5 GHz",
      ports: "2 x 1GbE",
      os: "RouterOS",
      warranty: "MikroTik hardware warranty",
      compliance: "CE",
    },
  },
  {
    title: "Ubiquiti EdgeRouter 4",
    handle: "ubiquiti-edgerouter-4",
    sku: "ER-4",
    manufacturer: "Ubiquiti",
    supplier_origin: "UK",
    description: para(
      "A compact wired router for small ISP edges and labs that still prefer EdgeOS.",
      "It suits sites that need SFP and three RJ45 routed ports without UniFi OS.",
      "Rack ears are not included. A shelf or cabinet mount should be planned.",
      "Ubiquiti limited hardware warranty applies."
    ),
    categories: ["Telecoms", "Telecoms Devices"],
    usd: 199,
    stock: 5,
    delivery_window_days: 9,
    sourcing_type: "in_stock",
    specs: {
      ports: "3 x 1GbE, 1 x SFP",
      os: "EdgeOS",
      form_factor: "Desktop",
      warranty: "Ubiquiti limited hardware",
      compliance: "Ubiquiti regulatory documentation",
    },
  },
  {
    title: "Yealink T46U handset",
    handle: "yealink-t46u",
    sku: "T46U",
    manufacturer: "Yealink",
    supplier_origin: "China",
    description: para(
      "A rugged-enough business SIP handset for reception, trading floors and contact desks that are not on Cisco UCM.",
      "It suits 3CX, Asterisk and other SIP platforms. We confirm the firmware train on the quote.",
      "PoE is standard. A power brick is optional. Headset adapters are a separate line.",
      "Yealink hardware warranty is two years unless the channel states otherwise."
    ),
    categories: ["Telecoms", "Telecoms Devices"],
    usd: 189,
    stock: 12,
    delivery_window_days: 16,
    sourcing_type: "in_stock",
    specs: {
      display: "4.3-inch colour",
      lines: "16 SIP accounts",
      power: "PoE 802.3af",
      warranty: "2-year Yealink hardware",
      compliance: "CE",
    },
  },
  {
    title: "Business Router Kit (Imports)",
    handle: "imports-business-router-kit",
    sku: "IMP-RTR-KIT-01",
    manufacturer: "Curated",
    supplier_origin: "China",
    description: para(
      "A curated SME branch router kit for sites that need a landed, specified import rather than a named carrier box.",
      "It suits pop-up branches and project sites where the exact OEM can vary by lot, but the port count and VPN features are fixed on the quote.",
      "The kit includes the router, power supply and a basic patch cable. Outdoor antennas are extra.",
      "Warranty is the importer's twelve months, stated on the quote. This is not an authorised-carrier SKU."
    ),
    categories: ["Imports"],
    usd: 449,
    stock: 8,
    delivery_window_days: 21,
    sourcing_type: "in_stock",
    specs: {
      ports: "Stated on quote, typically 4 LAN + 1 WAN",
      vpn: "IPsec / SSL, stated on quote",
      power: "Local 220 V brick",
      warranty: "12-month importer warranty",
      compliance: "Lot documentation supplied",
    },
  },
  {
    title: "APC Smart-UPS 1500VA",
    handle: "apc-smart-ups-1500va",
    sku: "SMT1500I",
    manufacturer: "APC",
    supplier_origin: "UK",
    description: para(
      "A 1500 VA line-interactive UPS for office servers, till systems and network closets that need clean shutdown time during load-shedding.",
      "It suits single-rack or under-desk loads. We will size runtime on the quote if you list the attached devices.",
      "The unit includes the UPS, a power cord and APC software entitlement. Network management cards are optional.",
      "APC standard warranty is two years electronics, two years battery, restated on the quote."
    ),
    categories: ["Imports"],
    usd: 689,
    stock: 4,
    delivery_window_days: 14,
    sourcing_type: "in_stock",
    specs: {
      capacity: "1500 VA / 1000 W",
      topology: "Line interactive",
      outlets: "IEC, count per SKU",
      runtime: "Sized on quote",
      warranty: "2-year APC, battery included",
      compliance: "CE",
    },
  },
  {
    title: "Eaton 5P 1550VA UPS",
    handle: "eaton-5p-1550va",
    sku: "5P1550i",
    manufacturer: "Eaton",
    supplier_origin: "UK",
    description: para(
      "A 1550 VA UPS alternative for sites that standardised on Eaton rather than APC.",
      "It suits network closets and POS back rooms. LCD metering is on the front panel.",
      "Network cards and extended batteries are quoted if you need remote management or longer runtime.",
      "Eaton warranty is stated on the quote, typically three years electronics."
    ),
    categories: ["Imports"],
    usd: 749,
    stock: 3,
    delivery_window_days: 16,
    sourcing_type: "pre_order",
    specs: {
      capacity: "1550 VA",
      topology: "Line interactive",
      form_factor: "Tower or rack convertible",
      warranty: "Eaton, stated on quote",
      compliance: "CE",
    },
  },
  {
    title: "Victron MultiPlus 48/5000 inverter",
    handle: "victron-multiplus-48-5000",
    sku: "PMP485021010",
    manufacturer: "Victron",
    supplier_origin: "UK",
    description: para(
      "A 48 V inverter/charger for sites that pair solar or generator input with a battery bank.",
      "It suits clinics, ISP POP sites and homes converted to hybrid power. A site electrical drawing is required before we finalise the quote.",
      "The quote lists the inverter, and separately the GX device, cabling and batteries if you want a complete string.",
      "Victron warranty is five years when registered, stated on the quote."
    ),
    categories: ["Imports"],
    usd: 1899,
    stock: 0,
    delivery_window_days: 21,
    sourcing_type: "pre_order",
    specs: {
      inverter: "5000 VA, 48 V",
      charger: "Integrated",
      transfer: "65 A",
      warranty: "5-year Victron when registered",
      compliance: "Victron regulatory documentation",
    },
  },
  {
    title: "Victron SmartSolar MPPT 150/45",
    handle: "victron-smartsolar-mppt-150-45",
    sku: "SCC115045212",
    manufacturer: "Victron",
    supplier_origin: "UK",
    description: para(
      "A 150 V / 45 A MPPT charge controller for small commercial solar strings.",
      "It suits sites adding panels to an existing 12, 24 or 48 V bank. String voltage is checked on the quote.",
      "Bluetooth setup is built in. A GX device is optional for remote logging.",
      "Victron warranty is five years when registered."
    ),
    categories: ["Imports"],
    usd: 329,
    stock: 6,
    delivery_window_days: 14,
    sourcing_type: "in_stock",
    specs: {
      pv_voltage: "150 V max",
      charge_current: "45 A",
      battery: "12 / 24 / 48 V",
      warranty: "5-year Victron when registered",
      compliance: "Victron regulatory documentation",
    },
  },
  {
    title: "Pylontech US3000C battery",
    handle: "pylontech-us3000c",
    sku: "US3000C",
    manufacturer: "Pylontech",
    supplier_origin: "China",
    description: para(
      "A 3.5 kWh lithium battery module for hybrid inverters that speak the Pylontech protocol.",
      "It suits stacked banks behind Victron, Sunsynk or similar inverters. Compatibility is confirmed on the quote.",
      "Each line is one module. Cables and a hub for larger stacks are extra.",
      "Pylontech warranty is typically ten years cycle-based. We copy the exact terms onto the quote."
    ),
    categories: ["Imports"],
    usd: 1190,
    stock: 0,
    delivery_window_days: 24,
    sourcing_type: "pre_order",
    specs: {
      energy: "3.5 kWh usable class",
      voltage: "48 V nominal",
      chemistry: "LiFePO4",
      warranty: "Pylontech cycle warranty on quote",
      compliance: "UN38.3, MSDS supplied",
    },
  },
  {
    title: "Anker 737 power bank 24K",
    handle: "anker-737-power-bank",
    sku: "A1289",
    manufacturer: "Anker",
    supplier_origin: "China",
    description: para(
      "A high-capacity USB-C power bank for field engineers and managers who lose grid for hours at a time.",
      "It suits laptops that charge over USB-C PD. We will not quote it as a substitute for a UPS.",
      "The carton includes the bank and a USB-C cable. Airline rules are the customer's responsibility.",
      "Anker limited warranty is two years."
    ),
    categories: ["Imports"],
    usd: 149,
    stock: 15,
    delivery_window_days: 12,
    sourcing_type: "in_stock",
    specs: {
      capacity: "24,000 mAh class",
      output: "USB-C PD, up to 140 W",
      warranty: "2-year Anker limited",
      compliance: "CE, air-transport limits apply",
    },
  },
  {
    title: "APC surge protection strip",
    handle: "apc-surge-protection-strip",
    sku: "PM5-UK",
    manufacturer: "APC",
    supplier_origin: "UK",
    description: para(
      "A five-outlet surge strip for desks and till points that need basic spike protection.",
      "It suits accessories next to a UPS, not as a replacement for one. Plug type is confirmed on the quote for Zimbabwe 220 V.",
      "A single strip is one line. Whole-office packs can be quoted.",
      "APC connected-equipment policy is printed on the carton and restated if you ask."
    ),
    categories: ["Imports"],
    usd: 49,
    stock: 30,
    delivery_window_days: 10,
    sourcing_type: "in_stock",
    specs: {
      outlets: "5",
      protection: "Surge suppression",
      voltage: "220 V, plug type on quote",
      warranty: "APC connected-equipment terms",
      compliance: "CE",
    },
  },
  {
    title: "HP LaserJet Pro 4002dw",
    handle: "hp-laserjet-pro-4002dw",
    sku: "2Z606A",
    manufacturer: "HP",
    supplier_origin: "UK",
    description: para(
      "A mono laser printer for offices that print contracts, delivery notes and internal forms all day.",
      "It suits shared floors that need duplex and Ethernet. Toner yields are listed on the quote if you want a starter pack.",
      "The printer ships with a starter cartridge. Extra toner is a separate import line.",
      "HP limited commercial warranty is one year, extendable on the quote."
    ),
    categories: ["Imports"],
    usd: 329,
    stock: 5,
    delivery_window_days: 14,
    sourcing_type: "in_stock",
    specs: {
      print: "Mono laser, duplex",
      speed: "Up to 40 ppm class",
      networking: "Ethernet and Wi-Fi",
      warranty: "1-year HP commercial, extendable",
      compliance: "Energy Star",
    },
  },
  {
    title: "Brother HL-L6400DW",
    handle: "brother-hl-l6400dw",
    sku: "HLL6400DWZU1",
    manufacturer: "Brother",
    supplier_origin: "UK",
    description: para(
      "A higher-duty mono laser for warehouses and shared print rooms that outgrow a desktop HP.",
      "It suits higher monthly volumes and optional tray expansion.",
      "Trays and toner packs are quoted as extras.",
      "Brother limited warranty is typically three years when registered."
    ),
    categories: ["Imports"],
    usd: 549,
    stock: 2,
    delivery_window_days: 16,
    sourcing_type: "pre_order",
    specs: {
      print: "Mono laser, duplex",
      duty: "Higher monthly duty than desktop class",
      networking: "Ethernet and Wi-Fi",
      warranty: "Brother, typically 3 years registered",
      compliance: "Energy Star",
    },
  },
  {
    title: "Dell 27-inch P2723D monitor",
    handle: "dell-p2723d-monitor",
    sku: "P2723D",
    manufacturer: "Dell",
    supplier_origin: "USA",
    description: para(
      "A 27-inch QHD business monitor for workstations and trading desks.",
      "It suits OptiPlex and ThinkPad users who need more pixels than a 24-inch FHD panel.",
      "The stand and power cable are included. A DisplayPort cable is in the box on most lots. HDMI-only sites should say so.",
      "Dell limited hardware warranty is three years."
    ),
    categories: ["Imports"],
    usd: 389,
    stock: 7,
    delivery_window_days: 14,
    sourcing_type: "in_stock",
    specs: {
      size: "27-inch",
      resolution: "QHD 2560 x 1440",
      inputs: "DisplayPort, HDMI",
      warranty: "3-year Dell limited hardware",
      compliance: "Energy Star, TCO",
    },
  },
  {
    title: "Huawei SUN2000 5KTL inverter",
    handle: "huawei-sun2000-5ktl",
    sku: "SUN2000-5KTL-L1",
    manufacturer: "Huawei",
    supplier_origin: "China",
    description: para(
      "A 5 kW single-phase string inverter for small commercial rooftops.",
      "It suits sites with a confirmed panel layout. We will not quote it without a string voltage check.",
      "Optimisers, dongles and batteries are separate lines.",
      "Huawei warranty is typically ten years on this series. We copy the exact terms onto the quote."
    ),
    categories: ["Imports"],
    usd: 799,
    stock: 0,
    delivery_window_days: 24,
    sourcing_type: "pre_order",
    specs: {
      ac_power: "5 kW",
      phase: "Single phase",
      mppt: "Dual MPPT",
      warranty: "Huawei, typically 10 years",
      compliance: "IEC, lot certificates supplied",
    },
  },
  {
    title: "CyberPower CP1500EPFCLCD",
    handle: "cyberpower-cp1500epfclcd",
    sku: "CP1500EPFCLCD",
    manufacturer: "CyberPower",
    supplier_origin: "China",
    description: para(
      "A PFC-compatible 1500 VA UPS for workstations and small NAS boxes that reject cheaper simulated sine units.",
      "It suits home-office and branch desks. Runtime is shorter than an APC Smart-UPS of the same VA. We will say so on the quote.",
      "Software is downloadable. A network card is not included.",
      "CyberPower warranty is typically two years."
    ),
    categories: ["Imports"],
    usd: 279,
    stock: 9,
    delivery_window_days: 16,
    sourcing_type: "in_stock",
    specs: {
      capacity: "1500 VA",
      output: "Pure sine, PFC compatible",
      display: "LCD",
      warranty: "2-year CyberPower typical",
      compliance: "CE",
    },
  },
  {
    title: "Sunsynk 5.5 kW hybrid inverter",
    handle: "sunsynk-5-5kw-hybrid",
    sku: "SUNSYNK-5.5K-SG01LP1",
    manufacturer: "Sunsynk",
    supplier_origin: "China",
    description: para(
      "A 5.5 kW hybrid inverter widely used on Southern African roofs that mix grid, solar and battery.",
      "It suits homes and small shops. A qualified installer and a single-line diagram are required before we place the order.",
      "Batteries, isolators and earthing material are quoted separately.",
      "Sunsynk warranty is stated on the quote, typically five to ten years depending on registration."
    ),
    categories: ["Imports"],
    usd: 1099,
    stock: 0,
    delivery_window_days: 21,
    sourcing_type: "pre_order",
    specs: {
      ac_power: "5.5 kW",
      type: "Hybrid, 48 V battery",
      phase: "Single phase",
      warranty: "Sunsynk, stated on quote",
      compliance: "Lot certificates supplied",
    },
  },
]

export function catalogByHandle(): Map<string, CatalogProduct> {
  return new Map(KONDUIT_CATALOG.map((product) => [product.handle, product]))
}

export function countByTopCategory(): Record<string, number> {
  const counts: Record<string, number> = {
    Infrastructure: 0,
    Telecoms: 0,
    Imports: 0,
  }
  for (const product of KONDUIT_CATALOG) {
    if (product.categories.includes("Infrastructure")) {
      counts.Infrastructure += 1
    }
    if (product.categories.includes("Telecoms")) {
      counts.Telecoms += 1
    }
    if (product.categories.includes("Imports")) {
      counts.Imports += 1
    }
  }
  return counts
}
